### ISSUE TITLE
Not obvious how to disable download progress bar

### ISSUE THREAD

**Issue by thk686** [walkerke/tigris#59]
I can't find it in the documentation. When rendering in RMarkdown, functions like states() fill pages with download progress. There needs to be a documented quiet option.

**Comment by walkerke** [comment]
I can do this.  However there are two ways to accomplish this right now: 

In your code chunk definition, set `results = "hide"` to suppress the progress bar from printing in the output document.  For example: 

```
```{r, results = "hide", message = FALSE, warning = FALSE}
library(tigris)

or <- roads("OR", "Benton")

plot(or)
```
```

The other alternative is to use cached files instead of downloading when knitting the RMarkdown document.  This can be accomplished with `options(tigris_use_cache = TRUE)`, which can go in your setup chunk if you don't want to show it.

**Comment by walkerke** [comment]
This is addressed in https://github.com/walkerke/tigris/commit/8b5dfe3637bc85918060e97fa29eb5921bbe9f01.  All tigris functions now can accept a logical `progress_bar` argument that if `FALSE` will disable the progress bar.  For example: 

```r
nh <- tracts("NH", cb = TRUE, progress_bar = FALSE)
```

will work for you.

**Comment by Johaning** [comment]
Thanks! I wanted to still show my code, just not the progress bar, and found that adding "progress_bar = FALSE" fixed the problem.
